gripper_effort_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - gripper_right_finger_joint
    - gripper_left_finger_joint

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.02

  gains: # Required because we're controlling an effort interface
    gripper_left_finger_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    gripper_right_finger_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}

    
